services:
  - type: worker
    name: dast-be-ab-bot
    runtime: python
    repo: https://github.com/aminoo13/dast-be-ab-bot
    branch: main
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TOKEN
        sync: false
